theme: jekyll-theme-cayman
title: 'PanoDR'
description: 'Spherical Panorama Diminished Reality for Indoor Scenes'
show_downloads: false
github:  
  owner_url: https://github.com/VasilisGks
  owner_name: Vasileios Gkitsas
